3
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import datetime

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import ttk, Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import tkinter as tk
import staff
from tkcalendar import Calendar, DateEntry
from tkinter.messagebox import askyesno


class SignUpForm(ttk.Frame):

    def __init__(self, container):
        super().__init__(container)
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / \
            Path(r"D:\Python\Python-Project\python\build\assets\frame0")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        # self.geometry("260x260")
        # self.configure(bg="#FFFFFF")

        self.canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=260,
            width=260,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        self.canvas.place(x=0, y=0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            129.0,
            152.0,
            image=self.entry_image_1
        )
        self.inputUserNameValue = tk.StringVar('')
        self.inputIdValue = tk.StringVar('')

        self.entry_1 = Entry(
            self,
            textvariable=self.inputUserNameValue,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(

            x=28.0,
            y=150.0,
            width=202.0,
            height=15.0
        )

        self.canvas.create_text(
            107.0,
            22.0,
            anchor="nw",
            text="Đăng ký",
            fill="#000000",
            font=("Inter", 12 * -1)
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            129.0,
            77.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            self,
            textvariable=self.inputIdValue,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=27.0,
            y=73.0,
            width=202.0,
            height=15.0
        )

        self.canvas.create_text(
            25.0,
            61.0,
            anchor="nw",
            text="Mã nhân viên\n\n\n\n\nTên nhân viên ",
            fill="#000000",
            font=("Inter", 12 * -1)
        )

        self.day = tk.StringVar('')
        self.calendar = DateEntry(self,
                                  selectmode='none', textvariable=self.day, date_pattern='yyyy/mm/dd')
        # self.calendar.pack(fill='x',expand=TRUE)
        self.calendar.place(x=100, y=177, width=140, height=20)
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.confirm_insert(container),
            relief="flat"
        )
        self.button_1.place(
            x=57.0,
            y=213.0,
            width=146.0,
            height=32.0
        )

        self.canvas.create_text(
            25.0,
            180.0,
            anchor="nw",
            text="Ngày sinh ",
            fill="#000000",
            font=("Inter", 12 * -1)
        )

    def confirm_insert(self, container):
        answer = askyesno(title="Confirm insert",
                          message='Bạn chắc chắn chứ ?')

        if answer:
            if self.inputIdValue.get() == '' or self.inputUserNameValue.get() == '' or self.day.get() == '':

                messagebox.showerror(
                    'Invalid input', 'Thông tin không được để trống')
                return
            if not self.inputIdValue.get().isdigit():
                messagebox.showerror(
                    'Invalid input', 'Mã cá nhân phải là số')
                return
            try:
                date_format = '%Y/%m/%d'
                datetime.datetime.strptime(self.day.get(), date_format)

            except ValueError:
                messagebox.showerror(
                    'Invalid input', 'Sai format ngày (YYYY-MM-DD)')
                return
            try:
                staff.insertStaff(
                    self.inputIdValue.get(), self.inputUserNameValue.get(), self.day.get()),
            except ValueError:
                messagebox.showerror(
                    'ERROR ⚠', 'Mã trùng')
                return
            messagebox.showinfo('Done!!!', "Đã tạo thành công")
            container.destroy()


if __name__ == "__main__":
    app = tk.Tk()
    frame = SignUpForm(app)
    frame.pack(fill=BOTH, expand=TRUE)
    app.geometry('400x400')
    app.mainloop()
